sudo: false
language: python
dist: trusty


matrix:
  include:
  - python: "2.6"
  - python: "2.7"
  - python: "3.2"
  - python: "3.3"
  - python: "3.4"
  - python: "3.5"
  - python: "3.6"
  - python: "3.7"
    dist: xenial
    sudo: required

branches:
  only:
    - staging
    - trying
    - master

install:
  - if [[ $TRAVIS_PYTHON_VERSION == "3.2" ]]; then travis_retry pip install --upgrade "setuptools<30.0.0"; fi
  - python setup.py build

script: "python test.py"
