# https://github.com/ogrisel/python-appveyor-demo/blob/master/appveyor.yml
environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"
    PYPI_USER: ifduyue
    PYPI_TEST_PASSWORD:
      secure: Ub5TGKonq/xFgzRLFMCcKQ==
    PYPI_PASSWORD:
      secure: fFfFN5N5920gtX3+pwrOddk/psDk3wK67snCOt209bc=

  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.1"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4.1"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.0"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.0"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.6"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.6"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python37"
      PYTHON_VERSION: "3.7.0"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.0"
      PYTHON_ARCH: "64"

    # build wheels
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.6"
      PYTHON_ARCH: "64"
      HIREDIS_PY_BUILDWHEELS: 1


install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "git submodule update --init --recursive"

build: off

test_script:
  - "%CMD_IN_ENV% python setup.py build"
  - "%CMD_IN_ENV% python test.py"
  - ps: |
      if (Test-Path env:HIREDIS_PY_BUILDWHEELS) {
        python -m pip install -U pip setuptools cibuildwheel
        cibuildwheel --output-dir wheels
        ls wheels
      }

artifacts:
  - path: wheels\*.whl
    name: Wheels

on_success:
    # deploy master non-tags to Test PyPI
    - ps: |
        if (!(Test-Path env:HIREDIS_PY_BUILDWHEELS)) { return }
        if (Test-Path env:APPVEYOR_PULL_REQUEST_NUMBER) { return }
        if ($env:APPVEYOR_REPO_NAME -ne 'redis/hiredis-py') { return }
        if ($env:APPVEYOR_REPO_BRANCH -ne 'master') { return }
        pip install -U twine
        twine upload -u $env:PYPI_USER -p $env:PYPI_TEST_PASSWORD --repository-url https://test.pypi.org/legacy/ --skip-existing wheels\*.whl

    # deploy tags to PyPI
    - ps: |
        if (!(Test-Path env:HIREDIS_PY_BUILDWHEELS)) { return }
        if (Test-Path env:APPVEYOR_PULL_REQUEST_NUMBER) { return }
        if ($env:APPVEYOR_REPO_NAME -ne 'redis/hiredis-py') { return }
        if ($env:APPVEYOR_REPO_TAG -ne 'true') { return }
        pip install -U twine
        twine upload -u $env:PYPI_USER -p $env:PYPI_PASSWORD --skip-existing wheels\*.whl
